# 🧮 NumPy Interview Preparation

This notebook collects high-value NumPy topics and concise examples you’ll commonly see in interviews: array creation, indexing, broadcasting, vectorized operations, performance, linear algebra, random, and common pitfalls.

## Setup: import NumPy and check version

In [21]:
import numpy as np
print('NumPy version:', np.__version__)


NumPy version: 2.4.2


## Array creation (common constructors)

In [22]:
# from list
a = np.array([1, 2, 3])
# zeros, ones, full, arange, linspace, eye, empty
z = np.zeros((2,3))
o = np.ones(3)
f = np.full((2,2), 7)
r = np.arange(0, 10, 2)
l = np.linspace(0, 1, 5)
I = np.eye(3)
print(a, ' \n', z, '\n ', o, ' \n', f, '\n ', r, '\n ', l, ' \n', I)


[1 2 3]  
 [[0. 0. 0.]
 [0. 0. 0.]] 
  [1. 1. 1.]  
 [[7 7]
 [7 7]] 
  [0 2 4 6 8] 
  [0.   0.25 0.5  0.75 1.  ]  
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Shapes, dtype, and basic attributes

In [23]:
arr = np.array([[1,2,3],[4,5,6]])
print('ndim:', arr.ndim)
print('shape:', arr.shape)
print('size:', arr.size)
print('dtype:', arr.dtype)


ndim: 2
shape: (2, 3)
size: 6
dtype: int64


## Indexing, slicing, fancy indexing and boolean masks

In [24]:
x = np.arange(10)
print(x[2:6])  # slice
print(x[[1,3,5]])  # fancy indexing (creates copy)
mask = x % 2 == 0
print('even:', x[mask])  # boolean indexing
# 2D indexing
m = np.arange(12).reshape(3,4)
print(m[1,2], m[0,:], m[:,1])


[2 3 4 5]
[1 3 5]
even: [0 2 4 6 8]
6 [0 1 2 3] [1 5 9]


## Views vs Copies (very important interview topic)

In [25]:
a = np.arange(10)
s = a[2:5]  # view (usually)
s[0] = 99
print('a after modifying view:', a)
# fancy indexing returns copy (no change to original)
b = a[[2,3,4]]
b[0] = -1
print('a after fancy-index copy modified:', a)


a after modifying view: [ 0  1 99  3  4  5  6  7  8  9]
a after fancy-index copy modified: [ 0  1 99  3  4  5  6  7  8  9]


## Broadcasting rules (concise explanation)

In [26]:
# broadcasting example: add vector to each row of matrix
mat = np.array([[1,2,3],[4,5,6]])
vec = np.array([10, 20, 30])
print(mat + vec)
# broadcasting with different shapes: (3,1) with (3,)
col = np.array([[1],[2],[3]])
row = np.array([10,20,30])
print(col + row)


[[11 22 33]
 [14 25 36]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


## Vectorized operations and reductions (fast vs Python loops)

In [27]:
a = np.arange(1_000_000)
# vectorized sum (C-optimized)
%timeit a.sum()
# Python loop (much slower)
def py_sum(x):
    s = 0
    for v in x:
        s += v
    return s

%timeit py_sum(a)


84.5 μs ± 11.1 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
29.7 ms ± 566 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Reshape, transpose, ravel, flatten, stacking

In [28]:
x = np.arange(12)
print('reshape:', x.reshape(3,4))
print('transpose:', x.reshape(3,4).T)
print('ravel (view):', x.reshape(3,4).ravel())
print('flatten (copy):', x.reshape(3,4).flatten())
# stacking
a = np.array([1,2,3])
b = np.array([4,5,6])
print('vstack:', np.vstack([a,b]))
print('hstack:', np.hstack([a,b]))


reshape: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transpose: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
ravel (view): [ 0  1  2  3  4  5  6  7  8  9 10 11]
flatten (copy): [ 0  1  2  3  4  5  6  7  8  9 10 11]
vstack: [[1 2 3]
 [4 5 6]]
hstack: [1 2 3 4 5 6]


## Datatypes and casting (astype)

In [29]:
x = np.array([1.5, 2.7, 3.1])
print(x.dtype)
y = x.astype(int)
print(y, y.dtype)
# careful with overflow and precision when casting


float64
[1 2 3] int64


## Linear algebra (dot, matmul, inv, svd)

In [30]:
A = np.array([[1.,2.],[3.,4.]])
b = np.array([1., 2.])
print('dot:', A.dot(b))
print('matmul:', A @ b)
print('inv:', np.linalg.inv(A))
print('eig:', np.linalg.eig(A))
print('svd:', np.linalg.svd(A))


dot: [ 5. 11.]
matmul: [ 5. 11.]
inv: [[-2.   1. ]
 [ 1.5 -0.5]]
eig: EigResult(eigenvalues=array([-0.37228132,  5.37228132]), eigenvectors=array([[-0.82456484, -0.41597356],
       [ 0.56576746, -0.90937671]]))
svd: SVDResult(U=array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]]), S=array([5.4649857 , 0.36596619]), Vh=array([[-0.57604844, -0.81741556],
       [ 0.81741556, -0.57604844]]))


## Random module (np.random) and seeding for reproducibility

In [31]:
np.random.seed(0)
print(np.random.rand(3))
print(np.random.randint(0, 10, size=(2,3)))


[0.5488135  0.71518937 0.60276338]
[[3 7 9]
 [3 5 2]]


## Performance tips and memory layout (C vs F order)

In [32]:
x = np.arange(12).reshape(3,4)
print('C contiguous:', x.flags['C_CONTIGUOUS'])
print('F contiguous:', x.flags['F_CONTIGUOUS'])
xf = np.asfortranarray(x)
print('after asfortran C contiguous:', xf.flags['C_CONTIGUOUS'])
print('after asfortran F contiguous:', xf.flags['F_CONTIGUOUS'])


C contiguous: True
F contiguous: False
after asfortran C contiguous: False
after asfortran F contiguous: True


## Common interview questions / exercises (with hints)

1. Given a 1D array, return the indices of the top-k largest elements.
2. Given a 2D array, compute the row-wise mean without explicit Python loops.
3. Implement a vectorized sliding window sum (convolution) for 1D arrays.
4. Given boolean mask and array, set all masked positions to 0 efficiently.
5. Explain broadcasting rules with examples.

In [33]:
# Example solution: top-k indices (question 1)
arr = np.random.rand(10)
k = 3
idx = np.argpartition(-arr, k-1)[:k]  # O(n) selection
print('top-k values:', arr[idx])
# sorted order of top-k
print('sorted top-k:', arr[np.argsort(-arr[idx])])


top-k values: [0.96366276 0.92559664 0.891773  ]
sorted top-k: [0.43758721 0.891773   0.96366276]


## Gotchas and pitfalls

- Be careful with shapes when broadcasting (read error messages).
- Watch out for integer division vs float (use dtype=float when needed).
- In-place operations can change dtypes or views unexpectedly.
- Use `np.copy()` when you need a true copy.
- Pay attention to memory order when interfacing with C/Fortran libraries.

---
**Next steps:** Practice the exercises above and read `numpy` docs on broadcasting and memory model for deeper understanding.

End of NumPy interview-prep.